// Stable aliases form the public vocabulary. Add a name only when a generic
// component or repeated platform interaction needs it.
export {
  AlertCircle as ErrorIcon,
  AlertTriangle as WarningIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUp as ArrowUpIcon,
  Bell as NotificationIcon,
  Calendar as CalendarIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  CircleHelp as HelpIcon,
  CirclePlus as AddCircleIcon,
  Clock as ClockIcon,
  Copy as CopyIcon,
  Download as DownloadIcon,
  Ellipsis as MoreIcon,
  EllipsisVertical as MoreVerticalIcon,
  ExternalLink as ExternalLinkIcon,
  Eye as VisibleIcon,
  EyeOff as HiddenIcon,
  File as FileIcon,
  Filter as FilterIcon,
  Folder as FolderIcon,
  House as HomeIcon,
  Info as InfoIcon,
  ListFilter as SortFilterIcon,
  LoaderCircle as LoadingIcon,
  Lock as LockIcon,
  LogOut as SignOutIcon,
  Mail as MailIcon,
  Menu as MenuIcon,
  Minus as RemoveIcon,
  PanelLeft as SidebarIcon,
  Pencil as EditIcon,
  Plus as AddIcon,
  RefreshCw as RefreshIcon,
  Save as SaveIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Trash2 as DeleteIcon,
  Unlock as UnlockIcon,
  Upload as UploadIcon,
  User as UserIcon,
  Users as UsersIcon,
  X as CloseIcon,
} from "@lucide/svelte";

export { default as IconBase } from "./IconBase.svelte";
export type { IconProps } from "./IconBase.svelte";
