import { create } from "storybook/theming";

export const agoraTheme = create({
  base: "dark",
  brandTitle: "Agora UI",
  colorPrimary: "var(--color-action-primary, #61b8e4)",
  colorSecondary: "var(--color-action-ghost-text, #ace3ff)",
  appBg: "var(--color-surface-canvas, #0f0f11)",
  appContentBg: "var(--color-surface-subtle, #1f1f22)",
  appHoverBg: "var(--color-action-ghost-hover, #313136)",
  appPreviewBg: "var(--color-surface-canvas, #0f0f11)",
  appBorderColor: "#434349",
  fontBase: "var(--font-family-interface, sans-serif)",
  fontCode: "var(--font-family-mono, monospace)",
  textColor: "var(--color-text-primary, #f1f1f4)",
  textInverseColor: "var(--color-action-primary-text, #0f0f11)",
  textMutedColor: "var(--color-text-muted, #d9dade)",
  barTextColor: "var(--color-text-muted, #d9dade)",
  barHoverColor: "var(--color-text-primary, #f1f1f4)",
  barSelectedColor: "var(--color-action-ghost-text, #ace3ff)",
  barBg: "var(--color-surface-subtle, #1f1f22)",
  buttonBg: "var(--color-surface-canvas, #0f0f11)",
  buttonBorder: "var(--color-border-subtle, #434349)",
  booleanBg: "var(--color-surface-canvas, #0f0f11)",
  booleanSelectedBg: "var(--color-action-ghost-hover, #313136)",
  inputBg: "var(--color-surface-canvas, #0f0f11)",
  inputBorder: "var(--color-border-subtle, #434349)",
  inputTextColor: "var(--color-text-primary, #f1f1f4)",
});
