import palette from "../src/color.tokens.json" with { type: "json" };

import { describe, expect, it } from "vitest";

// Guards the shape and validity of the generated OKLCH palette (see scripts/
// generate.ts). It is a fixture — regenerated by `pnpm generate` — so this
// asserts the contract every consumer relies on, not the exact colour values.
interface Token {
  $type: string;
  $value: string;
}
const color = (palette as { color: Record<string, Record<string, Token>> }).color;

const FAMILIES = ["neutral", "brand", "pressure", "success", "warning", "danger"];
const OKLCH = /^oklch\([\d.]+ [\d.]+ [\d.]+\)$/;

describe("OKLCH colour palette", () => {
  it("emits every seeded family", () => {
    expect(Object.keys(color).sort()).toEqual([...FAMILIES].sort());
  });

  it("gives each family a 12-step scale of valid oklch() values", () => {
    for (const family of FAMILIES) {
      const steps = color[family];
      expect(Object.keys(steps)).toHaveLength(12);
      for (let i = 1; i <= 12; i++) {
        expect(steps[String(i)].$type).toBe("color");
        expect(steps[String(i)].$value).toMatch(OKLCH);
      }
    }
  });

  it("ramps lightness monotonically from background to ink", () => {
    for (const family of FAMILIES) {
      const lightness = Object.values(color[family]).map((t) => Number(t.$value.slice(6).split(" ")[0]));
      for (let i = 1; i < lightness.length; i++) {
        expect(lightness[i]).toBeGreaterThan(lightness[i - 1]);
      }
    }
  });
});
