name: main

on:
  merge_group:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  lint-js:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/lint-node@v1.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          client_id: ${{ vars.DEPENDENCY_BOT_CLIENT_ID }}
          lint_action: "lint:ci"

  test-js:
    runs-on: ubuntu-latest
    needs:
      - lint-js
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/test-node@v1.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          client_id: ${{ vars.DEPENDENCY_BOT_CLIENT_ID }}
          test_action: "test:ci"

  report-codecov:
    runs-on: ubuntu-latest
    needs:
      - test-js
    permissions:
      contents: read
    steps:
      - uses: a-novel-kit/workflows/generic-actions/codecov@v1.23.0
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  build-js:
    needs:
      - test-js
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: a-novel-kit/workflows/node-actions/build-node@v1.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          app_private_key: ${{ secrets.DEPENDENCY_BOT_PRIVATE_KEY }}
          client_id: ${{ vars.DEPENDENCY_BOT_CLIENT_ID }}
